services:
  - type: web
    name: nifty-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: ANGEL_CLIENT_ID
        sync: false
      - key: ANGEL_API_KEY
        sync: false
      - key: ANGEL_SECRET_KEY
        sync: false
      - key: ANGEL_PASSWORD
        sync: false
      - key: ANGEL_TOTP_SECRET
        sync: false
